### ISSUE TITLE
How do you connect with tally?

### ISSUE THREAD

**Issue by ramesh-31** [TallyAssist/TallyAssist#12]
Hey, thanks for sharing the code. It's really nice of you guys.

Can you help me with how to connect this app with tally?

**Comment by RichaVerma** [comment]
Hi Ramesh, 

Sign up and download the apk from here - you will get a link to the tally connector in the app itself:  https://restat.co/download-tallyassist/

**Comment by swanav** [comment]
Are there plans to open source TallyConnector as well?

**Comment by viveknimkarde** [comment]
@RichaVerma tally connector download link is not working. can you please help with it.

**Comment by RichaVerma** [comment]
Hi there,

You can contact me on +91-7759091029 for reaching out directly.


*Richa Verma*
+91 7759 091 029

**Comment by hsbbangalore** [comment]
Hi @RichaVerma ,
Thanks for sharing the code for the app. Would further like to build upon it. If you can share the working link for tally connector it will be of great help. Thanks once again

**Comment by saivineeth100** [comment]
@RichaVerma @analyticalmonk 
Links are broken and unable to download Tally connector
Is Tally connector you mentioned is open source or proprietary
If open source leave the link here

I am developing a [tally Connector library in c# ](https://github.com/Accounting-Companion/TallyConnector) (Open-Sourced) so your existing code may help in pushing the library further

**Comment by RichaVerma** [comment]
Hi there,

The connector is proprietary and not open sourced. Thanks for building this
Tally Connector Library :)


*Richa Verma*
+91 7759 091 029

**Comment by saivineeth100** [comment]
ok
